API_KEY = '3HYFHHUOK76QYUQO'
ENDPOINT_SCHEMA_URL  = 'https://psrc-v7vorn.southeastasia.azure.confluent.cloud' #go to environment 
API_SECRET_KEY = 'nXZyuIGlkKBNCb/v/JvrfLixl8EU9YpQwU/RkU/i0/68bBWkckY5OcLMD3pB7FLt'
BOOTSTRAP_SERVER = 'pkc-7prvp.centralindia.azure.confluent.cloud:9092'
SECURITY_PROTOCOL = 'SASL_SSL'
SSL_MECHANISM = 'PLAIN'
SCHEMA_REGISTRY_API_KEY = 'NXSRRZ7NFSI2LSQ3'
SCHEMA_REGISTRY_API_SECRET = 'sEMXwibsggqWft9kWpb46l++XHcsPXCyaP7GoejppFypdMqtX+tPnLdsbbBu3lU8'


def config_values():
	return API_KEY, ENDPOINT_SCHEMA_URL, API_SECRET_KEY, BOOTSTRAP_SERVER, SECURITY_PROTOCOL, SSL_MECHANISM, SCHEMA_REGISTRY_API_KEY, SCHEMA_REGISTRY_API_SECRET
	